version: "3.1"

services:
  ####################### PPR Database Definition #######################
  ppr_db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: ppr
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ppr_db_data:/var/lib/postgresql/data

  #################### Jaeger Tracing Service Definition ####################
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"

volumes:
  ppr_db_data:
