version: "3.1"

services:
  #################### Jaeger Tracing Service Definition ####################
  jaeger:
    image: jaegertracing/all-in-one
    restart: always
    ports:
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
