apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ppr
      build: ${API_NAME}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: ${API_NAME}:latest
    source:
      contextDir: ims-api
      dockerfile: |
        FROM gradle:5.6.4-jdk11

        WORKDIR ims-api
        COPY . .
        EXPOSE 8080

        RUN gradle --no-daemon bootJar

        CMD ["java", "-jar", "build/libs/ims-api.jar"]
      git:
        uri: https://github.com/bcgov/ppr
      type: Git
    strategy:
      dockerStrategy: {}
    successfulBuildsHistoryLimit: 5
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ppr
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    lookupPolicy:
      local: false
parameters:
- description: The name of the API
  displayName: API Name
  name: API_NAME
  required: true
  value: ims-api
