apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ppr
      deploymentconfig: ${APP_NAME}
      role: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      app: ppr
      deploymentconfig: ${APP_NAME}
      environment: ${ENVIRONMENT}
      role: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ppr
          deploymentconfig: ${APP_NAME}
          environment: ${ENVIRONMENT}
          role: ${APP_NAME}
      spec:
        containers:
          - args: # Start Caddy inside the Docker image
            - /tmp/scripts/run
            imagePullPolicy: Always
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 2015
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: ${APP_NAME}
            ports:
            - containerPort: 2015
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 2015
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            resources:
              limits:
                cpu: '1'
                memory: 250Mi
              requests:
                cpu: 10m
                memory: 100Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/www/html/config
                name: ppr-web-ui-config
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: ppr-web-ui-config
            name: ppr-web-ui-config
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:${IMAGE_TAG}
          namespace: zwmtib-tools
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ppr
      environment: ${ENVIRONMENT}
      role: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 2015-tcp
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ppr
      environment: ${ENVIRONMENT}
      role: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${ROUTE_URL}
    port:
      targetPort: 2015-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name of the Web application.
  displayName: APP Name
  name: APP_NAME
  required: true
  value: ppr-ui
- description: The environment, such as "dev", "dev-pr13", "test", or "prod".
  displayName: Environment
  name: ENVIRONMENT
  required: true
  value: dev
- description: The image tag to build from.
  displayName: Image Tag
  name: IMAGE_TAG
  required: true
  value: dev
- description: The URL to use for the route.
  displayName: Route URL
  name: ROUTE_URL
  required: true
  value: ppr-dev.pathfinder.gov.bc.ca
- description: Volume name for web app config
  displayName: Web application config volume mount name
  name: VOL_APP_CONFIG
  required: true
  value: ppr-web-ui-config
- description: Volume name for caddy config
  displayName: Caddy config volume mount name
  name: VOL_CADDY
  required: true
  value: ppr-web-caddy-config
#- description: The path at which web application is deployed. Context root for the web applicaton
#  displayName: WEB_APP_CONTEXT_PATH
#  name: WEB_APP_CONTEXT_PATH
#  required: true
#  value: ppr
