apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: ppr-ui
      dockerfile: |
        FROM node:8
        COPY . .
        RUN npm install
        RUN npm run build
        # RUN ls -alR /dist
      git:
        uri: https://github.com/bcgov/ppr
        # sample how to use a developer's fork
        # uri: https://github.com/somedeveloper/ppr
        # Defaults to shallow clone of master so no need to ref master. If you do set ref to master then clone is deep
        # Sample to show how to override to a branch
        # ref: branch
      type: Git
    strategy:
      dockerStrategy:
        noCache: false
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
parameters:
- description: The name of the intermediate build image for the PPR UI
  displayName: APP Name
  name: APP_NAME
  required: true
  value: ppr-ui-inter

