"""create_address_tables

Revision ID: 6411b673d98b
Revises: 947ffeeeda60
Create Date: 2020-01-29 08:07:05.926797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6411b673d98b'
down_revision = '947ffeeeda60'
branch_labels = None
depends_on = None


def upgrade():

    country_type_table = op.create_table(
        'country_type',
        sa.Column('country_type_cd', sa.CHAR(length=2), primary_key=True),
        sa.Column('description', sa.String(length=75))
    )

    op.bulk_insert(country_type_table, [
        {'country_type_cd': 'AD', 'description': 'ANDORRA'},
        {'country_type_cd': 'AE', 'description': 'UNITED ARAB EMIRATES'},
        {'country_type_cd': 'AF', 'description': 'AFGHANISTAN'},
        {'country_type_cd': 'AG', 'description': 'ANTIGUA AND BARBUDA'},
        {'country_type_cd': 'AI', 'description': 'ANGUILLA'},
        {'country_type_cd': 'AL', 'description': 'ALBANIA'},
        {'country_type_cd': 'AM', 'description': 'ARMENIA'},
        {'country_type_cd': 'AN', 'description': 'NETHERLANDS ANTILLES'},
        {'country_type_cd': 'AO', 'description': 'ANGOLA'},
        {'country_type_cd': 'AQ', 'description': 'ANTARCTICA'},
        {'country_type_cd': 'AR', 'description': 'ARGENTINA'},
        {'country_type_cd': 'AS', 'description': 'AMERICAN SAMOA'},
        {'country_type_cd': 'AT', 'description': 'AUSTRIA'},
        {'country_type_cd': 'AU', 'description': 'AUSTRALIA'},
        {'country_type_cd': 'AW', 'description': 'ARUBA'},
        {'country_type_cd': 'AX', 'description': 'ALAND ISLANDS'},
        {'country_type_cd': 'AZ', 'description': 'AZERBAIJAN'},
        {'country_type_cd': 'BA', 'description': 'BOSNIA AND HERZEGOVINA'},
        {'country_type_cd': 'BB', 'description': 'BARBADOS'},
        {'country_type_cd': 'BD', 'description': 'BANGLADESH'},
        {'country_type_cd': 'BE', 'description': 'BELGIUM'},
        {'country_type_cd': 'BF', 'description': 'BURKINA FASO'},
        {'country_type_cd': 'BG', 'description': 'BULGARIA'},
        {'country_type_cd': 'BH', 'description': 'BAHRAIN'},
        {'country_type_cd': 'BI', 'description': 'BURUNDI'},
        {'country_type_cd': 'BJ', 'description': 'BENIN'},
        {'country_type_cd': 'BL', 'description': 'SAINT BARTHELEMY'},
        {'country_type_cd': 'BM', 'description': 'BERMUDA'},
        {'country_type_cd': 'BN', 'description': 'BRUNEI DARUSSALAM'},
        {'country_type_cd': 'BO', 'description': 'BOLIVIA'},
        {'country_type_cd': 'BQ', 'description': 'BONAIRE, ST EUSTATIUS AND SABA'},
        {'country_type_cd': 'BR', 'description': 'BRAZIL'},
        {'country_type_cd': 'BS', 'description': 'BAHAMAS'},
        {'country_type_cd': 'BT', 'description': 'BHUTAN'},
        {'country_type_cd': 'BV', 'description': 'BOUVET ISLAND'},
        {'country_type_cd': 'BW', 'description': 'BOTSWANA'},
        {'country_type_cd': 'BY', 'description': 'BELARUS'},
        {'country_type_cd': 'BZ', 'description': 'BELIZE'},
        {'country_type_cd': 'CA', 'description': 'CANADA'},
        {'country_type_cd': 'CC', 'description': 'COCOS (KEELING) ISLANDS'},
        {'country_type_cd': 'CD', 'description': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE'},
        {'country_type_cd': 'CF', 'description': 'CENTRAL AFRICAN REPUBLIC'},
        {'country_type_cd': 'CG', 'description': 'CONGO'},
        {'country_type_cd': 'CH', 'description': 'SWITZERLAND'},
        {'country_type_cd': 'CI', 'description': 'COTE D''IVOIRE'},
        {'country_type_cd': 'CK', 'description': 'COOK ISLANDS'},
        {'country_type_cd': 'CL', 'description': 'CHILE'},
        {'country_type_cd': 'CM', 'description': 'CAMEROON'},
        {'country_type_cd': 'CN', 'description': 'CHINA'},
        {'country_type_cd': 'CO', 'description': 'COLOMBIA'},
        {'country_type_cd': 'CR', 'description': 'COSTA RICA'},
        {'country_type_cd': 'CU', 'description': 'CUBA'},
        {'country_type_cd': 'CV', 'description': 'CAPE VERDE'},
        {'country_type_cd': 'CW', 'description': 'CURACAO'},
        {'country_type_cd': 'CX', 'description': 'CHRISTMAS ISLAND'},
        {'country_type_cd': 'CY', 'description': 'CYPRUS'},
        {'country_type_cd': 'CZ', 'description': 'CZECH REPUBLIC'},
        {'country_type_cd': 'DE', 'description': 'GERMANY'},
        {'country_type_cd': 'DJ', 'description': 'DJIBOUTI'},
        {'country_type_cd': 'DK', 'description': 'DENMARK'},
        {'country_type_cd': 'DM', 'description': 'DOMINICA'},
        {'country_type_cd': 'DO', 'description': 'DOMINICAN REPUBLIC'},
        {'country_type_cd': 'DZ', 'description': 'ALGERIA'},
        {'country_type_cd': 'EC', 'description': 'ECUADOR'},
        {'country_type_cd': 'EE', 'description': 'ESTONIA'},
        {'country_type_cd': 'EG', 'description': 'EGYPT'},
        {'country_type_cd': 'EH', 'description': 'WESTERN SAHARA'},
        {'country_type_cd': 'ER', 'description': 'ERITREA'},
        {'country_type_cd': 'ES', 'description': 'SPAIN'},
        {'country_type_cd': 'ET', 'description': 'ETHIOPIA'},
        {'country_type_cd': 'FI', 'description': 'FINLAND'},
        {'country_type_cd': 'FJ', 'description': 'FIJI'},
        {'country_type_cd': 'FK', 'description': 'FALKLAND ISLANDS (MALVINAS)'},
        {'country_type_cd': 'FM', 'description': 'MICRONESIA, FEDERATED STATES OF'},
        {'country_type_cd': 'FO', 'description': 'FAROE ISLANDS'},
        {'country_type_cd': 'FR', 'description': 'FRANCE'},
        {'country_type_cd': 'FX', 'description': 'FRANCE, METROPOLITAN'},
        {'country_type_cd': 'GA', 'description': 'GABON'},
        {'country_type_cd': 'GB', 'description': 'UNITED KINGDOM'},
        {'country_type_cd': 'GD', 'description': 'GRENADA'},
        {'country_type_cd': 'GE', 'description': 'GEORGIA'},
        {'country_type_cd': 'GF', 'description': 'FRENCH GUIANA'},
        {'country_type_cd': 'GG', 'description': 'GUERNSEY'},
        {'country_type_cd': 'GH', 'description': 'GHANA'},
        {'country_type_cd': 'GI', 'description': 'GIBRALTAR'},
        {'country_type_cd': 'GL', 'description': 'GREENLAND'},
        {'country_type_cd': 'GM', 'description': 'GAMBIA'},
        {'country_type_cd': 'GN', 'description': 'GUINEA'},
        {'country_type_cd': 'GP', 'description': 'GUADELOUPE'},
        {'country_type_cd': 'GQ', 'description': 'EQUATORIAL GUINEA'},
        {'country_type_cd': 'GR', 'description': 'GREECE'},
        {'country_type_cd': 'GS', 'description': 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL'},
        {'country_type_cd': 'GT', 'description': 'GUATEMALA'},
        {'country_type_cd': 'GU', 'description': 'GUAM'},
        {'country_type_cd': 'GW', 'description': 'GUINEA-BISSAU'},
        {'country_type_cd': 'GY', 'description': 'GUYANA'},
        {'country_type_cd': 'HK', 'description': 'HONG KONG'},
        {'country_type_cd': 'HM', 'description': 'HEARD ISLAND AND MCDONALD ISLANDS'},
        {'country_type_cd': 'HN', 'description': 'HONDURAS'},
        {'country_type_cd': 'HR', 'description': 'CROATIA'},
        {'country_type_cd': 'HT', 'description': 'HAITI'},
        {'country_type_cd': 'HU', 'description': 'HUNGARY'},
        {'country_type_cd': 'ID', 'description': 'INDONESIA'},
        {'country_type_cd': 'IE', 'description': 'IRELAND'},
        {'country_type_cd': 'IL', 'description': 'ISRAEL'},
        {'country_type_cd': 'IM', 'description': 'ISLE OF MAN'},
        {'country_type_cd': 'IN', 'description': 'INDIA'},
        {'country_type_cd': 'IO', 'description': 'BRITISH INDIAN OCEAN TERRITORY'},
        {'country_type_cd': 'IQ', 'description': 'IRAQ'},
        {'country_type_cd': 'IR', 'description': 'IRAN, ISLAMIC REPUBLIC OF'},
        {'country_type_cd': 'IS', 'description': 'ICELAND'},
        {'country_type_cd': 'IT', 'description': 'ITALY'},
        {'country_type_cd': 'JE', 'description': 'JERSEY'},
        {'country_type_cd': 'JM', 'description': 'JAMAICA'},
        {'country_type_cd': 'JO', 'description': 'JORDAN'},
        {'country_type_cd': 'JP', 'description': 'JAPAN'},
        {'country_type_cd': 'KE', 'description': 'KENYA'},
        {'country_type_cd': 'KG', 'description': 'KYRGYZSTAN'},
        {'country_type_cd': 'KH', 'description': 'CAMBODIA'},
        {'country_type_cd': 'KI', 'description': 'KIRIBATI'},
        {'country_type_cd': 'KM', 'description': 'COMOROS'},
        {'country_type_cd': 'KN', 'description': 'SAINT KITTS AND NEVIS'},
        {'country_type_cd': 'KP', 'description': 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF'},
        {'country_type_cd': 'KR', 'description': 'KOREA, REPUBLIC OF'},
        {'country_type_cd': 'KW', 'description': 'KUWAIT'},
        {'country_type_cd': 'KY', 'description': 'CAYMAN ISLANDS'},
        {'country_type_cd': 'KZ', 'description': 'KAZAKHSTAN'},
        {'country_type_cd': 'LA', 'description': 'LAO PEOPLE''S DEMOCRATIC REPUBLIC'},
        {'country_type_cd': 'LB', 'description': 'LEBANON'},
        {'country_type_cd': 'LC', 'description': 'SAINT LUCIA'},
        {'country_type_cd': 'LI', 'description': 'LIECHTENSTEIN'},
        {'country_type_cd': 'LK', 'description': 'SRI LANKA'},
        {'country_type_cd': 'LR', 'description': 'LIBERIA'},
        {'country_type_cd': 'LS', 'description': 'LESOTHO'},
        {'country_type_cd': 'LT', 'description': 'LITHUANIA'},
        {'country_type_cd': 'LU', 'description': 'LUXEMBOURG'},
        {'country_type_cd': 'LV', 'description': 'LATVIA'},
        {'country_type_cd': 'LY', 'description': 'LIBYA'},
        {'country_type_cd': 'MA', 'description': 'MOROCCO'},
        {'country_type_cd': 'MC', 'description': 'MONACO'},
        {'country_type_cd': 'MD', 'description': 'MOLDOVA, REPUBLIC OF'},
        {'country_type_cd': 'ME', 'description': 'MONTENEGRO'},
        {'country_type_cd': 'MF', 'description': 'SAINT MARTIN(FRENCH PART)'},
        {'country_type_cd': 'MG', 'description': 'MADAGASCAR'},
        {'country_type_cd': 'MH', 'description': 'MARSHALL ISLANDS'},
        {'country_type_cd': 'MK', 'description': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC'},
        {'country_type_cd': 'ML', 'description': 'MALI'},
        {'country_type_cd': 'MM', 'description': 'MYANMAR'},
        {'country_type_cd': 'MN', 'description': 'MONGOLIA'},
        {'country_type_cd': 'MO', 'description': 'MACAO'},
        {'country_type_cd': 'MP', 'description': 'NORTHERN MARIANA ISLANDS'},
        {'country_type_cd': 'MQ', 'description': 'MARTINIQUE'},
        {'country_type_cd': 'MR', 'description': 'MAURITANIA'},
        {'country_type_cd': 'MS', 'description': 'MONTSERRAT'},
        {'country_type_cd': 'MT', 'description': 'MALTA'},
        {'country_type_cd': 'MU', 'description': 'MAURITIUS'},
        {'country_type_cd': 'MV', 'description': 'MALDIVES'},
        {'country_type_cd': 'MW', 'description': 'MALAWI'},
        {'country_type_cd': 'MX', 'description': 'MEXICO'},
        {'country_type_cd': 'MY', 'description': 'MALAYSIA'},
        {'country_type_cd': 'MZ', 'description': 'MOZAMBIQUE'},
        {'country_type_cd': 'NA', 'description': 'NAMIBIA'},
        {'country_type_cd': 'NC', 'description': 'NEW CALEDONIA'},
        {'country_type_cd': 'NE', 'description': 'NIGER'},
        {'country_type_cd': 'NF', 'description': 'NORFOLK ISLAND'},
        {'country_type_cd': 'NG', 'description': 'NIGERIA'},
        {'country_type_cd': 'NI', 'description': 'NICARAGUA'},
        {'country_type_cd': 'NL', 'description': 'NETHERLANDS'},
        {'country_type_cd': 'NO', 'description': 'NORWAY'},
        {'country_type_cd': 'NP', 'description': 'NEPAL'},
        {'country_type_cd': 'NR', 'description': 'NAURU'},
        {'country_type_cd': 'NU', 'description': 'NIUE'},
        {'country_type_cd': 'NZ', 'description': 'NEW ZEALAND'},
        {'country_type_cd': 'OM', 'description': 'OMAN'},
        {'country_type_cd': 'PA', 'description': 'PANAMA'},
        {'country_type_cd': 'PE', 'description': 'PERU'},
        {'country_type_cd': 'PF', 'description': 'FRENCH POLYNESIA'},
        {'country_type_cd': 'PG', 'description': 'PAPUA NEW GUINEA'},
        {'country_type_cd': 'PH', 'description': 'PHILIPPINES'},
        {'country_type_cd': 'PK', 'description': 'PAKISTAN'},
        {'country_type_cd': 'PL', 'description': 'POLAND'},
        {'country_type_cd': 'PM', 'description': 'SAINT PIERRE AND MIQUELON'},
        {'country_type_cd': 'PN', 'description': 'PITCAIRN'},
        {'country_type_cd': 'PR', 'description': 'PUERTO RICO'},
        {'country_type_cd': 'PS', 'description': 'PALESTINIAN TERRITORY, OCCUPIED'},
        {'country_type_cd': 'PT', 'description': 'PORTUGAL'},
        {'country_type_cd': 'PW', 'description': 'PALAU'},
        {'country_type_cd': 'PY', 'description': 'PARAGUAY'},
        {'country_type_cd': 'QA', 'description': 'QATAR'},
        {'country_type_cd': 'RE', 'description': 'REUNION'},
        {'country_type_cd': 'RO', 'description': 'ROMANIA'},
        {'country_type_cd': 'RS', 'description': 'SERBIA'},
        {'country_type_cd': 'RU', 'description': 'RUSSIAN FEDERATION'},
        {'country_type_cd': 'RW', 'description': 'RWANDA'},
        {'country_type_cd': 'SA', 'description': 'SAUDI ARABIA'},
        {'country_type_cd': 'SB', 'description': 'SOLOMON ISLANDS'},
        {'country_type_cd': 'SC', 'description': 'SEYCHELLES'},
        {'country_type_cd': 'SD', 'description': 'SUDAN'},
        {'country_type_cd': 'SE', 'description': 'SWEDEN'},
        {'country_type_cd': 'SG', 'description': 'SINGAPORE'},
        {'country_type_cd': 'SH', 'description': 'SAINT HELENA'},
        {'country_type_cd': 'SI', 'description': 'SLOVENIA'},
        {'country_type_cd': 'SJ', 'description': 'SVALBARD AND JAN MAYEN'},
        {'country_type_cd': 'SK', 'description': 'SLOVAKIA'},
        {'country_type_cd': 'SL', 'description': 'SIERRA LEONE'},
        {'country_type_cd': 'SM', 'description': 'SAN MARINO'},
        {'country_type_cd': 'SN', 'description': 'SENEGAL'},
        {'country_type_cd': 'SO', 'description': 'SOMALIA'},
        {'country_type_cd': 'SR', 'description': 'SURINAME'},
        {'country_type_cd': 'SS', 'description': 'SOUTH SUDAN'},
        {'country_type_cd': 'ST', 'description': 'SAO TOME AND PRINCIPE'},
        {'country_type_cd': 'SV', 'description': 'EL SALVADOR'},
        {'country_type_cd': 'SX', 'description': 'SINT MAARTEN(DUTCH PART)'},
        {'country_type_cd': 'SY', 'description': 'SYRIAN ARAB REPUBLIC'},
        {'country_type_cd': 'SZ', 'description': 'SWAZILAND'},
        {'country_type_cd': 'TA', 'description': 'TRISTAN DA CUNHA'},
        {'country_type_cd': 'TC', 'description': 'TURKS AND CAICOS ISLANDS'},
        {'country_type_cd': 'TD', 'description': 'CHAD'},
        {'country_type_cd': 'TF', 'description': 'FRENCH SOUTHERN TERRITORIES'},
        {'country_type_cd': 'TG', 'description': 'TOGO'},
        {'country_type_cd': 'TH', 'description': 'THAILAND'},
        {'country_type_cd': 'TJ', 'description': 'TAJIKISTAN'},
        {'country_type_cd': 'TK', 'description': 'TOKELAU'},
        {'country_type_cd': 'TL', 'description': 'TIMOR-LESTE'},
        {'country_type_cd': 'TM', 'description': 'TURKMENISTAN'},
        {'country_type_cd': 'TN', 'description': 'TUNISIA'},
        {'country_type_cd': 'TO', 'description': 'TONGA'},
        {'country_type_cd': 'TR', 'description': 'TURKEY'},
        {'country_type_cd': 'TT', 'description': 'TRINIDAD AND TOBAGO'},
        {'country_type_cd': 'TV', 'description': 'TUVALU'},
        {'country_type_cd': 'TW', 'description': 'TAIWAN'},
        {'country_type_cd': 'TZ', 'description': 'TANZANIA, UNITED REPUBLIC OF'},
        {'country_type_cd': 'UA', 'description': 'UKRAINE'},
        {'country_type_cd': 'UG', 'description': 'UGANDA'},
        {'country_type_cd': 'UM', 'description': 'UNITED STATES MINOR OUTLYING ISLANDS'},
        {'country_type_cd': 'US', 'description': 'UNITED STATES'},
        {'country_type_cd': 'UY', 'description': 'URUGUAY'},
        {'country_type_cd': 'UZ', 'description': 'UZBEKISTAN'},
        {'country_type_cd': 'VA', 'description': 'HOLY SEE (VATICAN CITY STATE)'},
        {'country_type_cd': 'VC', 'description': 'SAINT VINCENT AND THE GRENADINES'},
        {'country_type_cd': 'VE', 'description': 'VENEZUELA'},
        {'country_type_cd': 'VG', 'description': 'VIRGIN ISLANDS, BRITISH'},
        {'country_type_cd': 'VI', 'description': 'VIRGIN ISLANDS, U.S.'},
        {'country_type_cd': 'VN', 'description': 'VIET NAM'},
        {'country_type_cd': 'VU', 'description': 'VANUATU'},
        {'country_type_cd': 'WF', 'description': 'WALLIS AND FUTUNA'},
        {'country_type_cd': 'WS', 'description': 'SAMOA'},
        {'country_type_cd': 'XZ', 'description': 'KOSOVO'},
        {'country_type_cd': 'YE', 'description': 'YEMEN'},
        {'country_type_cd': 'YT', 'description': 'MAYOTTE'},
        {'country_type_cd': 'YU', 'description': 'YUGOSLAVIA'},
        {'country_type_cd': 'ZA', 'description': 'SOUTH AFRICA'},
        {'country_type_cd': 'ZM', 'description': 'ZAMBIA'},
        {'country_type_cd': 'ZW', 'description': 'ZIMBABWE'}
    ])

    prov_state_type_table = op.create_table(
        'prov_state_type',
        sa.Column('province', sa.CHAR(length=2), primary_key=True),
        sa.Column('country_type_cd', sa.CHAR(length=2), sa.ForeignKey('country_type.country_type_cd')),
        sa.Column('description', sa.String(length=75))
    )

    op.bulk_insert(prov_state_type_table, [
        {'province': 'AA', 'country_type_cd': 'US', 'description': 'ARMED FORCES - AMERICAS'},
        {'province': 'AB', 'country_type_cd': 'CA', 'description': 'ALBERTA'},
        {'province': 'AE', 'country_type_cd': 'US', 'description': 'ARMED FORCES - OTHER'},
        {'province': 'AK', 'country_type_cd': 'US', 'description': 'ALASKA'},
        {'province': 'AL', 'country_type_cd': 'US', 'description': 'ALABAMA'},
        {'province': 'AP', 'country_type_cd': 'US', 'description': 'ARMED FORCES - PACIFIC'},
        {'province': 'AR', 'country_type_cd': 'US', 'description': 'ARKANSAS'},
        {'province': 'AS', 'country_type_cd': 'US', 'description': 'AMERICAN SAMOA'},
        {'province': 'AZ', 'country_type_cd': 'US', 'description': 'ARIZONA'},
        {'province': 'BC', 'country_type_cd': 'CA', 'description': 'BRITISH COLUMBIA'},
        {'province': 'CA', 'country_type_cd': 'US', 'description': 'CALIFORNIA'},
        {'province': 'CO', 'country_type_cd': 'US', 'description': 'COLORADO'},
        {'province': 'CT', 'country_type_cd': 'US', 'description': 'CONNECTICUT'},
        {'province': 'DC', 'country_type_cd': 'US', 'description': 'DISTRICT OF COLUMBIA'},
        {'province': 'DE', 'country_type_cd': 'US', 'description': 'DELAWARE'},
        {'province': 'FL', 'country_type_cd': 'US', 'description': 'FLORIDA'},
        {'province': 'FM', 'country_type_cd': 'US', 'description': 'FED. STATES'},
        {'province': 'GA', 'country_type_cd': 'US', 'description': 'GEORGIA'},
        {'province': 'GU', 'country_type_cd': 'US', 'description': 'GUAM'},
        {'province': 'HI', 'country_type_cd': 'US', 'description': 'HAWAII'},
        {'province': 'IA', 'country_type_cd': 'US', 'description': 'IOWA'},
        {'province': 'ID', 'country_type_cd': 'US', 'description': 'IDAHO'},
        {'province': 'IL', 'country_type_cd': 'US', 'description': 'ILLINOIS'},
        {'province': 'IN', 'country_type_cd': 'US', 'description': 'INDIANA'},
        {'province': 'KS', 'country_type_cd': 'US', 'description': 'KANSAS'},
        {'province': 'KY', 'country_type_cd': 'US', 'description': 'KENTUCKY'},
        {'province': 'LA', 'country_type_cd': 'US', 'description': 'LOUISIANA'},
        {'province': 'MA', 'country_type_cd': 'US', 'description': 'MASSACHUSETTS'},
        {'province': 'MB', 'country_type_cd': 'CA', 'description': 'MANITOBA'},
        {'province': 'MD', 'country_type_cd': 'US', 'description': 'MARYLAND'},
        {'province': 'ME', 'country_type_cd': 'US', 'description': 'MAINE'},
        {'province': 'MH', 'country_type_cd': 'US', 'description': 'MARSHALL ISLANDS'},
        {'province': 'MI', 'country_type_cd': 'US', 'description': 'MICHIGAN'},
        {'province': 'MN', 'country_type_cd': 'US', 'description': 'MINNESOTA'},
        {'province': 'MO', 'country_type_cd': 'US', 'description': 'MISSOURI'},
        {'province': 'MP', 'country_type_cd': 'US', 'description': 'N. MARIANA ISLANDS'},
        {'province': 'MS', 'country_type_cd': 'US', 'description': 'MISSISSIPPI'},
        {'province': 'MT', 'country_type_cd': 'US', 'description': 'MONTANA'},
        {'province': 'NB', 'country_type_cd': 'CA', 'description': 'NEW BRUNSWICK'},
        {'province': 'NC', 'country_type_cd': 'US', 'description': 'NORTH CAROLINA'},
        {'province': 'ND', 'country_type_cd': 'US', 'description': 'NORTH DAKOTA'},
        {'province': 'NE', 'country_type_cd': 'US', 'description': 'NEBRASKA'},
        {'province': 'NH', 'country_type_cd': 'US', 'description': 'NEW HAMPSHIRE'},
        {'province': 'NJ', 'country_type_cd': 'US', 'description': 'NEW JERSEY'},
        {'province': 'NL', 'country_type_cd': 'CA', 'description': 'NEWFOUNDLAND AND LABRADOR'},
        {'province': 'NM', 'country_type_cd': 'US', 'description': 'NEW MEXICO'},
        {'province': 'NS', 'country_type_cd': 'CA', 'description': 'NOVA SCOTIA'},
        {'province': 'NT', 'country_type_cd': 'CA', 'description': 'NORTHWEST TERRITORIES'},
        {'province': 'NU', 'country_type_cd': 'CA', 'description': 'NUNAVUT'},
        {'province': 'NV', 'country_type_cd': 'US', 'description': 'NEVADA'},
        {'province': 'NY', 'country_type_cd': 'US', 'description': 'NEW YORK'},
        {'province': 'OH', 'country_type_cd': 'US', 'description': 'OHIO'},
        {'province': 'OK', 'country_type_cd': 'US', 'description': 'OKLAHOMA'},
        {'province': 'ON', 'country_type_cd': 'CA', 'description': 'ONTARIO'},
        {'province': 'OR', 'country_type_cd': 'US', 'description': 'OREGON'},
        {'province': 'PA', 'country_type_cd': 'US', 'description': 'PENNSYLVANIA'},
        {'province': 'PE', 'country_type_cd': 'CA', 'description': 'PRINCE EDWARD ISLAND'},
        {'province': 'PR', 'country_type_cd': 'US', 'description': 'PUERTO RICO'},
        {'province': 'PW', 'country_type_cd': 'US', 'description': 'PALAU'},
        {'province': 'QC', 'country_type_cd': 'CA', 'description': 'QUEBEC'},
        {'province': 'RI', 'country_type_cd': 'US', 'description': 'RHODE ISLAND'},
        {'province': 'SC', 'country_type_cd': 'US', 'description': 'SOUTH CAROLINA'},
        {'province': 'SD', 'country_type_cd': 'US', 'description': 'SOUTH DAKOTA'},
        {'province': 'SK', 'country_type_cd': 'CA', 'description': 'SASKATCHEWAN'},
        {'province': 'TN', 'country_type_cd': 'US', 'description': 'TENNESSEE'},
        {'province': 'TX', 'country_type_cd': 'US', 'description': 'TEXAS'},
        {'province': 'UM', 'country_type_cd': 'US', 'description': 'U.S. MINOR ISLANDS'},
        {'province': 'UT', 'country_type_cd': 'US', 'description': 'UTAH'},
        {'province': 'VA', 'country_type_cd': 'US', 'description': 'VIRGINIA'},
        {'province': 'VI', 'country_type_cd': 'US', 'description': 'VIRGIN ISLANDS'},
        {'province': 'VT', 'country_type_cd': 'US', 'description': 'VERMONT'},
        {'province': 'WA', 'country_type_cd': 'US', 'description': 'WASHINGTON'},
        {'province': 'WI', 'country_type_cd': 'US', 'description': 'WISCONSIN'},
        {'province': 'WV', 'country_type_cd': 'US', 'description': 'WEST VIRGINIA'},
        {'province': 'WY', 'country_type_cd': 'US', 'description': 'WYOMING'},
        {'province': 'YT', 'country_type_cd': 'CA', 'description': 'YUKON TERRITORIES'}
    ])

    op.create_table(
        'address',
        sa.Column('addr_id', sa.BigInteger, primary_key=True),
        sa.Column('province', sa.CHAR(length=2), sa.ForeignKey('prov_state_type.province')),
        sa.Column('country_type_cd', sa.CHAR(length=2), sa.ForeignKey('country_type.country_type_cd')),
        sa.Column('postal_cd', sa.String(15)),
        sa.Column('addr_line_1', sa.String(50)),
        sa.Column('addr_line_2', sa.String(50)),
        sa.Column('addr_line_3', sa.String(50)),
        sa.Column('city', sa.String(40)),
        sa.Column('address_format_type', sa.String(10)),
        sa.Column('address_desc', sa.String(300)),
        sa.Column('address_desc_short', sa.String(300))
    )


def downgrade():
    op.drop_table('address')
    op.drop_table('prov_state_type')
    op.drop_table('country_type')
