"""Create address tables.

Revision ID: 6411b673d98b
Revises: 947ffeeeda60
Create Date: 2020-01-29 08:07:05.926797

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '6411b673d98b'
down_revision = '947ffeeeda60'
branch_labels = None
depends_on = None


def upgrade():

    country_type_table = op.create_table(
        'country_type',
        sa.Column('country_type_cd', sa.CHAR(length=2), primary_key=True),
        sa.Column('description', sa.String(length=75))
    )

    op.bulk_insert(country_type_table, [
        {'country_type_cd': 'AD', 'description': 'Andorra'},
        {'country_type_cd': 'AE', 'description': 'United Arab Emirates'},
        {'country_type_cd': 'AF', 'description': 'Afghanistan'},
        {'country_type_cd': 'AG', 'description': 'Antigua And Barbuda'},
        {'country_type_cd': 'AI', 'description': 'Anguilla'},
        {'country_type_cd': 'AL', 'description': 'Albania'},
        {'country_type_cd': 'AM', 'description': 'Armenia'},
        {'country_type_cd': 'AN', 'description': 'Netherlands Antilles'},
        {'country_type_cd': 'AO', 'description': 'Angola'},
        {'country_type_cd': 'AQ', 'description': 'Antarctica'},
        {'country_type_cd': 'AR', 'description': 'Argentina'},
        {'country_type_cd': 'AS', 'description': 'American Samoa'},
        {'country_type_cd': 'AT', 'description': 'Austria'},
        {'country_type_cd': 'AU', 'description': 'Australia'},
        {'country_type_cd': 'AW', 'description': 'Aruba'},
        {'country_type_cd': 'AX', 'description': 'Aland Islands'},
        {'country_type_cd': 'AZ', 'description': 'Azerbaijan'},
        {'country_type_cd': 'BA', 'description': 'Bosnia And Herzegovina'},
        {'country_type_cd': 'BB', 'description': 'Barbados'},
        {'country_type_cd': 'BD', 'description': 'Bangladesh'},
        {'country_type_cd': 'BE', 'description': 'Belgium'},
        {'country_type_cd': 'BF', 'description': 'Burkina Faso'},
        {'country_type_cd': 'BG', 'description': 'Bulgaria'},
        {'country_type_cd': 'BH', 'description': 'Bahrain'},
        {'country_type_cd': 'BI', 'description': 'Burundi'},
        {'country_type_cd': 'BJ', 'description': 'Benin'},
        {'country_type_cd': 'BL', 'description': 'Saint Barthelemy'},
        {'country_type_cd': 'BM', 'description': 'Bermuda'},
        {'country_type_cd': 'BN', 'description': 'Brunei Darussalam'},
        {'country_type_cd': 'BO', 'description': 'Bolivia'},
        {'country_type_cd': 'BQ', 'description': 'Bonaire, St Eustatius And Saba'},
        {'country_type_cd': 'BR', 'description': 'Brazil'},
        {'country_type_cd': 'BS', 'description': 'Bahamas'},
        {'country_type_cd': 'BT', 'description': 'Bhutan'},
        {'country_type_cd': 'BV', 'description': 'Bouvet Island'},
        {'country_type_cd': 'BW', 'description': 'Botswana'},
        {'country_type_cd': 'BY', 'description': 'Belarus'},
        {'country_type_cd': 'BZ', 'description': 'Belize'},
        {'country_type_cd': 'CA', 'description': 'Canada'},
        {'country_type_cd': 'CC', 'description': 'Cocos (Keeling) Islands'},
        {'country_type_cd': 'CD', 'description': 'Congo, The Democratic Republic Of The'},
        {'country_type_cd': 'CF', 'description': 'Central African Republic'},
        {'country_type_cd': 'CG', 'description': 'Congo'},
        {'country_type_cd': 'CH', 'description': 'Switzerland'},
        {'country_type_cd': 'CI', 'description': "Cote D'Ivoire"},
        {'country_type_cd': 'CK', 'description': 'Cook Islands'},
        {'country_type_cd': 'CL', 'description': 'Chile'},
        {'country_type_cd': 'CM', 'description': 'Cameroon'},
        {'country_type_cd': 'CN', 'description': 'China'},
        {'country_type_cd': 'CO', 'description': 'Colombia'},
        {'country_type_cd': 'CR', 'description': 'Costa Rica'},
        {'country_type_cd': 'CU', 'description': 'Cuba'},
        {'country_type_cd': 'CV', 'description': 'Cape Verde'},
        {'country_type_cd': 'CW', 'description': 'Curacao'},
        {'country_type_cd': 'CX', 'description': 'Christmas Island'},
        {'country_type_cd': 'CY', 'description': 'Cyprus'},
        {'country_type_cd': 'CZ', 'description': 'Czech Republic'},
        {'country_type_cd': 'DE', 'description': 'Germany'},
        {'country_type_cd': 'DJ', 'description': 'Djibouti'},
        {'country_type_cd': 'DK', 'description': 'Denmark'},
        {'country_type_cd': 'DM', 'description': 'Dominica'},
        {'country_type_cd': 'DO', 'description': 'Dominican Republic'},
        {'country_type_cd': 'DZ', 'description': 'Algeria'},
        {'country_type_cd': 'EC', 'description': 'Ecuador'},
        {'country_type_cd': 'EE', 'description': 'Estonia'},
        {'country_type_cd': 'EG', 'description': 'Egypt'},
        {'country_type_cd': 'EH', 'description': 'Western Sahara'},
        {'country_type_cd': 'ER', 'description': 'Eritrea'},
        {'country_type_cd': 'ES', 'description': 'Spain'},
        {'country_type_cd': 'ET', 'description': 'Ethiopia'},
        {'country_type_cd': 'FI', 'description': 'Finland'},
        {'country_type_cd': 'FJ', 'description': 'Fiji'},
        {'country_type_cd': 'FK', 'description': 'Falkland Islands (Malvinas)'},
        {'country_type_cd': 'FM', 'description': 'Micronesia, Federated States Of'},
        {'country_type_cd': 'FO', 'description': 'Faroe Islands'},
        {'country_type_cd': 'FR', 'description': 'France'},
        {'country_type_cd': 'FX', 'description': 'France, Metropolitan'},
        {'country_type_cd': 'GA', 'description': 'Gabon'},
        {'country_type_cd': 'GB', 'description': 'United Kingdom'},
        {'country_type_cd': 'GD', 'description': 'Grenada'},
        {'country_type_cd': 'GE', 'description': 'Georgia'},
        {'country_type_cd': 'GF', 'description': 'French Guiana'},
        {'country_type_cd': 'GG', 'description': 'Guernsey'},
        {'country_type_cd': 'GH', 'description': 'Ghana'},
        {'country_type_cd': 'GI', 'description': 'Gibraltar'},
        {'country_type_cd': 'GL', 'description': 'Greenland'},
        {'country_type_cd': 'GM', 'description': 'Gambia'},
        {'country_type_cd': 'GN', 'description': 'Guinea'},
        {'country_type_cd': 'GP', 'description': 'Guadeloupe'},
        {'country_type_cd': 'GQ', 'description': 'Equatorial Guinea'},
        {'country_type_cd': 'GR', 'description': 'Greece'},
        {'country_type_cd': 'GS', 'description': 'South Georgia And The South Sandwich Isl'},
        {'country_type_cd': 'GT', 'description': 'Guatemala'},
        {'country_type_cd': 'GU', 'description': 'Guam'},
        {'country_type_cd': 'GW', 'description': 'Guinea-Bissau'},
        {'country_type_cd': 'GY', 'description': 'Guyana'},
        {'country_type_cd': 'HK', 'description': 'Hong Kong'},
        {'country_type_cd': 'HM', 'description': 'Heard Island And Mcdonald Islands'},
        {'country_type_cd': 'HN', 'description': 'Honduras'},
        {'country_type_cd': 'HR', 'description': 'Croatia'},
        {'country_type_cd': 'HT', 'description': 'Haiti'},
        {'country_type_cd': 'HU', 'description': 'Hungary'},
        {'country_type_cd': 'ID', 'description': 'Indonesia'},
        {'country_type_cd': 'IE', 'description': 'Ireland'},
        {'country_type_cd': 'IL', 'description': 'Israel'},
        {'country_type_cd': 'IM', 'description': 'Isle Of Man'},
        {'country_type_cd': 'IN', 'description': 'India'},
        {'country_type_cd': 'IO', 'description': 'British Indian Ocean Territory'},
        {'country_type_cd': 'IQ', 'description': 'Iraq'},
        {'country_type_cd': 'IR', 'description': 'Iran, Islamic Republic Of'},
        {'country_type_cd': 'IS', 'description': 'Iceland'},
        {'country_type_cd': 'IT', 'description': 'Italy'},
        {'country_type_cd': 'JE', 'description': 'Jersey'},
        {'country_type_cd': 'JM', 'description': 'Jamaica'},
        {'country_type_cd': 'JO', 'description': 'Jordan'},
        {'country_type_cd': 'JP', 'description': 'Japan'},
        {'country_type_cd': 'KE', 'description': 'Kenya'},
        {'country_type_cd': 'KG', 'description': 'Kyrgyzstan'},
        {'country_type_cd': 'KH', 'description': 'Cambodia'},
        {'country_type_cd': 'KI', 'description': 'Kiribati'},
        {'country_type_cd': 'KM', 'description': 'Comoros'},
        {'country_type_cd': 'KN', 'description': 'Saint Kitts And Nevis'},
        {'country_type_cd': 'KP', 'description': 'Korea, Democratic People''S Republic Of'},
        {'country_type_cd': 'KR', 'description': 'Korea, Republic Of'},
        {'country_type_cd': 'KW', 'description': 'Kuwait'},
        {'country_type_cd': 'KY', 'description': 'Cayman Islands'},
        {'country_type_cd': 'KZ', 'description': 'Kazakhstan'},
        {'country_type_cd': 'LA', 'description': 'Lao People''S Democratic Republic'},
        {'country_type_cd': 'LB', 'description': 'Lebanon'},
        {'country_type_cd': 'LC', 'description': 'Saint Lucia'},
        {'country_type_cd': 'LI', 'description': 'Liechtenstein'},
        {'country_type_cd': 'LK', 'description': 'Sri Lanka'},
        {'country_type_cd': 'LR', 'description': 'Liberia'},
        {'country_type_cd': 'LS', 'description': 'Lesotho'},
        {'country_type_cd': 'LT', 'description': 'Lithuania'},
        {'country_type_cd': 'LU', 'description': 'Luxembourg'},
        {'country_type_cd': 'LV', 'description': 'Latvia'},
        {'country_type_cd': 'LY', 'description': 'Libya'},
        {'country_type_cd': 'MA', 'description': 'Morocco'},
        {'country_type_cd': 'MC', 'description': 'Monaco'},
        {'country_type_cd': 'MD', 'description': 'Moldova, Republic Of'},
        {'country_type_cd': 'ME', 'description': 'Montenegro'},
        {'country_type_cd': 'MF', 'description': 'Saint Martin(French Part)'},
        {'country_type_cd': 'MG', 'description': 'Madagascar'},
        {'country_type_cd': 'MH', 'description': 'Marshall Islands'},
        {'country_type_cd': 'MK', 'description': 'Macedonia, The Former Yugoslav Republic'},
        {'country_type_cd': 'ML', 'description': 'Mali'},
        {'country_type_cd': 'MM', 'description': 'Myanmar'},
        {'country_type_cd': 'MN', 'description': 'Mongolia'},
        {'country_type_cd': 'MO', 'description': 'Macao'},
        {'country_type_cd': 'MP', 'description': 'Northern Mariana Islands'},
        {'country_type_cd': 'MQ', 'description': 'Martinique'},
        {'country_type_cd': 'MR', 'description': 'Mauritania'},
        {'country_type_cd': 'MS', 'description': 'Montserrat'},
        {'country_type_cd': 'MT', 'description': 'Malta'},
        {'country_type_cd': 'MU', 'description': 'Mauritius'},
        {'country_type_cd': 'MV', 'description': 'Maldives'},
        {'country_type_cd': 'MW', 'description': 'Malawi'},
        {'country_type_cd': 'MX', 'description': 'Mexico'},
        {'country_type_cd': 'MY', 'description': 'Malaysia'},
        {'country_type_cd': 'MZ', 'description': 'Mozambique'},
        {'country_type_cd': 'NA', 'description': 'Namibia'},
        {'country_type_cd': 'NC', 'description': 'New Caledonia'},
        {'country_type_cd': 'NE', 'description': 'Niger'},
        {'country_type_cd': 'NF', 'description': 'Norfolk Island'},
        {'country_type_cd': 'NG', 'description': 'Nigeria'},
        {'country_type_cd': 'NI', 'description': 'Nicaragua'},
        {'country_type_cd': 'NL', 'description': 'Netherlands'},
        {'country_type_cd': 'NO', 'description': 'Norway'},
        {'country_type_cd': 'NP', 'description': 'Nepal'},
        {'country_type_cd': 'NR', 'description': 'Nauru'},
        {'country_type_cd': 'NU', 'description': 'Niue'},
        {'country_type_cd': 'NZ', 'description': 'New Zealand'},
        {'country_type_cd': 'OM', 'description': 'Oman'},
        {'country_type_cd': 'PA', 'description': 'Panama'},
        {'country_type_cd': 'PE', 'description': 'Peru'},
        {'country_type_cd': 'PF', 'description': 'French Polynesia'},
        {'country_type_cd': 'PG', 'description': 'Papua New Guinea'},
        {'country_type_cd': 'PH', 'description': 'Philippines'},
        {'country_type_cd': 'PK', 'description': 'Pakistan'},
        {'country_type_cd': 'PL', 'description': 'Poland'},
        {'country_type_cd': 'PM', 'description': 'Saint Pierre And Miquelon'},
        {'country_type_cd': 'PN', 'description': 'Pitcairn'},
        {'country_type_cd': 'PR', 'description': 'Puerto Rico'},
        {'country_type_cd': 'PS', 'description': 'Palestinian Territory, Occupied'},
        {'country_type_cd': 'PT', 'description': 'Portugal'},
        {'country_type_cd': 'PW', 'description': 'Palau'},
        {'country_type_cd': 'PY', 'description': 'Paraguay'},
        {'country_type_cd': 'QA', 'description': 'Qatar'},
        {'country_type_cd': 'RE', 'description': 'Reunion'},
        {'country_type_cd': 'RO', 'description': 'Romania'},
        {'country_type_cd': 'RS', 'description': 'Serbia'},
        {'country_type_cd': 'RU', 'description': 'Russian Federation'},
        {'country_type_cd': 'RW', 'description': 'Rwanda'},
        {'country_type_cd': 'SA', 'description': 'Saudi Arabia'},
        {'country_type_cd': 'SB', 'description': 'Solomon Islands'},
        {'country_type_cd': 'SC', 'description': 'Seychelles'},
        {'country_type_cd': 'SD', 'description': 'Sudan'},
        {'country_type_cd': 'SE', 'description': 'Sweden'},
        {'country_type_cd': 'SG', 'description': 'Singapore'},
        {'country_type_cd': 'SH', 'description': 'Saint Helena'},
        {'country_type_cd': 'SI', 'description': 'Slovenia'},
        {'country_type_cd': 'SJ', 'description': 'Svalbard And Jan Mayen'},
        {'country_type_cd': 'SK', 'description': 'Slovakia'},
        {'country_type_cd': 'SL', 'description': 'Sierra Leone'},
        {'country_type_cd': 'SM', 'description': 'San Marino'},
        {'country_type_cd': 'SN', 'description': 'Senegal'},
        {'country_type_cd': 'SO', 'description': 'Somalia'},
        {'country_type_cd': 'SR', 'description': 'Suriname'},
        {'country_type_cd': 'SS', 'description': 'South Sudan'},
        {'country_type_cd': 'ST', 'description': 'Sao Tome And Principe'},
        {'country_type_cd': 'SV', 'description': 'El Salvador'},
        {'country_type_cd': 'SX', 'description': 'Sint Maarten(Dutch Part)'},
        {'country_type_cd': 'SY', 'description': 'Syrian Arab Republic'},
        {'country_type_cd': 'SZ', 'description': 'Swaziland'},
        {'country_type_cd': 'TA', 'description': 'Tristan Da Cunha'},
        {'country_type_cd': 'TC', 'description': 'Turks And Caicos Islands'},
        {'country_type_cd': 'TD', 'description': 'Chad'},
        {'country_type_cd': 'TF', 'description': 'French Southern Territories'},
        {'country_type_cd': 'TG', 'description': 'Togo'},
        {'country_type_cd': 'TH', 'description': 'Thailand'},
        {'country_type_cd': 'TJ', 'description': 'Tajikistan'},
        {'country_type_cd': 'TK', 'description': 'Tokelau'},
        {'country_type_cd': 'TL', 'description': 'Timor-Leste'},
        {'country_type_cd': 'TM', 'description': 'Turkmenistan'},
        {'country_type_cd': 'TN', 'description': 'Tunisia'},
        {'country_type_cd': 'TO', 'description': 'Tonga'},
        {'country_type_cd': 'TR', 'description': 'Turkey'},
        {'country_type_cd': 'TT', 'description': 'Trinidad And Tobago'},
        {'country_type_cd': 'TV', 'description': 'Tuvalu'},
        {'country_type_cd': 'TW', 'description': 'Taiwan'},
        {'country_type_cd': 'TZ', 'description': 'Tanzania, United Republic Of'},
        {'country_type_cd': 'UA', 'description': 'Ukraine'},
        {'country_type_cd': 'UG', 'description': 'Uganda'},
        {'country_type_cd': 'UM', 'description': 'United States Minor Outlying Islands'},
        {'country_type_cd': 'US', 'description': 'United States'},
        {'country_type_cd': 'UY', 'description': 'Uruguay'},
        {'country_type_cd': 'UZ', 'description': 'Uzbekistan'},
        {'country_type_cd': 'VA', 'description': 'Holy See (Vatican City State)'},
        {'country_type_cd': 'VC', 'description': 'Saint Vincent And The Grenadines'},
        {'country_type_cd': 'VE', 'description': 'Venezuela'},
        {'country_type_cd': 'VG', 'description': 'Virgin Islands, British'},
        {'country_type_cd': 'VI', 'description': 'Virgin Islands, U.S.'},
        {'country_type_cd': 'VN', 'description': 'Viet Nam'},
        {'country_type_cd': 'VU', 'description': 'Vanuatu'},
        {'country_type_cd': 'WF', 'description': 'Wallis And Futuna'},
        {'country_type_cd': 'WS', 'description': 'Samoa'},
        {'country_type_cd': 'XZ', 'description': 'Kosovo'},
        {'country_type_cd': 'YE', 'description': 'Yemen'},
        {'country_type_cd': 'YT', 'description': 'Mayotte'},
        {'country_type_cd': 'YU', 'description': 'Yugoslavia'},
        {'country_type_cd': 'ZA', 'description': 'South Africa'},
        {'country_type_cd': 'ZM', 'description': 'Zambia'},
        {'country_type_cd': 'ZW', 'description': 'Zimbabwe'}
    ])

    prov_state_type_table = op.create_table(
        'prov_state_type',
        sa.Column('province', sa.CHAR(length=2), primary_key=True),
        sa.Column('country_type_cd', sa.CHAR(length=2), sa.ForeignKey('country_type.country_type_cd')),
        sa.Column('description', sa.String(length=75))
    )

    op.bulk_insert(prov_state_type_table, [
        {'province': 'AA', 'country_type_cd': 'US', 'description': 'Armed Forces - Americas'},
        {'province': 'AB', 'country_type_cd': 'CA', 'description': 'Alberta'},
        {'province': 'AE', 'country_type_cd': 'US', 'description': 'Armed Forces - Other'},
        {'province': 'AK', 'country_type_cd': 'US', 'description': 'Alaska'},
        {'province': 'AL', 'country_type_cd': 'US', 'description': 'Alabama'},
        {'province': 'AP', 'country_type_cd': 'US', 'description': 'Armed Forces - Pacific'},
        {'province': 'AR', 'country_type_cd': 'US', 'description': 'Arkansas'},
        {'province': 'AS', 'country_type_cd': 'US', 'description': 'American Samoa'},
        {'province': 'AZ', 'country_type_cd': 'US', 'description': 'Arizona'},
        {'province': 'BC', 'country_type_cd': 'CA', 'description': 'British Columbia'},
        {'province': 'CA', 'country_type_cd': 'US', 'description': 'California'},
        {'province': 'CO', 'country_type_cd': 'US', 'description': 'Colorado'},
        {'province': 'CT', 'country_type_cd': 'US', 'description': 'Connecticut'},
        {'province': 'DC', 'country_type_cd': 'US', 'description': 'District Of Columbia'},
        {'province': 'DE', 'country_type_cd': 'US', 'description': 'Delaware'},
        {'province': 'FL', 'country_type_cd': 'US', 'description': 'Florida'},
        {'province': 'FM', 'country_type_cd': 'US', 'description': 'Fed. States'},
        {'province': 'GA', 'country_type_cd': 'US', 'description': 'Georgia'},
        {'province': 'GU', 'country_type_cd': 'US', 'description': 'Guam'},
        {'province': 'HI', 'country_type_cd': 'US', 'description': 'Hawaii'},
        {'province': 'IA', 'country_type_cd': 'US', 'description': 'Iowa'},
        {'province': 'ID', 'country_type_cd': 'US', 'description': 'Idaho'},
        {'province': 'IL', 'country_type_cd': 'US', 'description': 'Illinois'},
        {'province': 'IN', 'country_type_cd': 'US', 'description': 'Indiana'},
        {'province': 'KS', 'country_type_cd': 'US', 'description': 'Kansas'},
        {'province': 'KY', 'country_type_cd': 'US', 'description': 'Kentucky'},
        {'province': 'LA', 'country_type_cd': 'US', 'description': 'Louisiana'},
        {'province': 'MA', 'country_type_cd': 'US', 'description': 'Massachusetts'},
        {'province': 'MB', 'country_type_cd': 'CA', 'description': 'Manitoba'},
        {'province': 'MD', 'country_type_cd': 'US', 'description': 'Maryland'},
        {'province': 'ME', 'country_type_cd': 'US', 'description': 'Maine'},
        {'province': 'MH', 'country_type_cd': 'US', 'description': 'Marshall Islands'},
        {'province': 'MI', 'country_type_cd': 'US', 'description': 'Michigan'},
        {'province': 'MN', 'country_type_cd': 'US', 'description': 'Minnesota'},
        {'province': 'MO', 'country_type_cd': 'US', 'description': 'Missouri'},
        {'province': 'MP', 'country_type_cd': 'US', 'description': 'N. Mariana Islands'},
        {'province': 'MS', 'country_type_cd': 'US', 'description': 'Mississippi'},
        {'province': 'MT', 'country_type_cd': 'US', 'description': 'Montana'},
        {'province': 'NB', 'country_type_cd': 'CA', 'description': 'New Brunswick'},
        {'province': 'NC', 'country_type_cd': 'US', 'description': 'North Carolina'},
        {'province': 'ND', 'country_type_cd': 'US', 'description': 'North Dakota'},
        {'province': 'NE', 'country_type_cd': 'US', 'description': 'Nebraska'},
        {'province': 'NH', 'country_type_cd': 'US', 'description': 'New Hampshire'},
        {'province': 'NJ', 'country_type_cd': 'US', 'description': 'New Jersey'},
        {'province': 'NL', 'country_type_cd': 'CA', 'description': 'Newfoundland And Labrador'},
        {'province': 'NM', 'country_type_cd': 'US', 'description': 'New Mexico'},
        {'province': 'NS', 'country_type_cd': 'CA', 'description': 'Nova Scotia'},
        {'province': 'NT', 'country_type_cd': 'CA', 'description': 'Northwest Territories'},
        {'province': 'NU', 'country_type_cd': 'CA', 'description': 'Nunavut'},
        {'province': 'NV', 'country_type_cd': 'US', 'description': 'Nevada'},
        {'province': 'NY', 'country_type_cd': 'US', 'description': 'New York'},
        {'province': 'OH', 'country_type_cd': 'US', 'description': 'Ohio'},
        {'province': 'OK', 'country_type_cd': 'US', 'description': 'Oklahoma'},
        {'province': 'ON', 'country_type_cd': 'CA', 'description': 'Ontario'},
        {'province': 'OR', 'country_type_cd': 'US', 'description': 'Oregon'},
        {'province': 'PA', 'country_type_cd': 'US', 'description': 'Pennsylvania'},
        {'province': 'PE', 'country_type_cd': 'CA', 'description': 'Prince Edward Island'},
        {'province': 'PR', 'country_type_cd': 'US', 'description': 'Puerto Rico'},
        {'province': 'PW', 'country_type_cd': 'US', 'description': 'Palau'},
        {'province': 'QC', 'country_type_cd': 'CA', 'description': 'Quebec'},
        {'province': 'RI', 'country_type_cd': 'US', 'description': 'Rhode Island'},
        {'province': 'SC', 'country_type_cd': 'US', 'description': 'South Carolina'},
        {'province': 'SD', 'country_type_cd': 'US', 'description': 'South Dakota'},
        {'province': 'SK', 'country_type_cd': 'CA', 'description': 'Saskatchewan'},
        {'province': 'TN', 'country_type_cd': 'US', 'description': 'Tennessee'},
        {'province': 'TX', 'country_type_cd': 'US', 'description': 'Texas'},
        {'province': 'UM', 'country_type_cd': 'US', 'description': 'U.S. Minor Islands'},
        {'province': 'UT', 'country_type_cd': 'US', 'description': 'Utah'},
        {'province': 'VA', 'country_type_cd': 'US', 'description': 'Virginia'},
        {'province': 'VI', 'country_type_cd': 'US', 'description': 'Virgin Islands'},
        {'province': 'VT', 'country_type_cd': 'US', 'description': 'Vermont'},
        {'province': 'WA', 'country_type_cd': 'US', 'description': 'Washington'},
        {'province': 'WI', 'country_type_cd': 'US', 'description': 'Wisconsin'},
        {'province': 'WV', 'country_type_cd': 'US', 'description': 'West Virginia'},
        {'province': 'WY', 'country_type_cd': 'US', 'description': 'Wyoming'},
        {'province': 'YT', 'country_type_cd': 'CA', 'description': 'Yukon Territories'}
    ])

    op.create_table(
        'address',
        sa.Column('addr_id', sa.BigInteger, primary_key=True),
        sa.Column('province', sa.CHAR(length=2), sa.ForeignKey('prov_state_type.province')),
        sa.Column('country_type_cd', sa.CHAR(length=2), sa.ForeignKey('country_type.country_type_cd')),
        sa.Column('postal_cd', sa.String(15)),
        sa.Column('addr_line_1', sa.String(50)),
        sa.Column('addr_line_2', sa.String(50)),
        sa.Column('addr_line_3', sa.String(50)),
        sa.Column('city', sa.String(40)),
        sa.Column('address_format_type', sa.String(10)),
        sa.Column('address_desc', sa.String(300)),
        sa.Column('address_desc_short', sa.String(300))
    )


def downgrade():
    op.drop_table('address')
    op.drop_table('prov_state_type')
    op.drop_table('country_type')
