apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ppr
      deploymentconfig: ${API_NAME}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      app: ppr
      deploymentconfig: ${API_NAME}
      environment: ${ENVIRONMENT}
      role: ${API_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ppr
          deploymentconfig: ${API_NAME}
          environment: ${ENVIRONMENT}
          role: ${API_NAME}
      spec:
        containers:
        - env:
          - name: PORT
            value: "8080"
          - name: PPR_API_ALLOWED_ORIGINS
            value: ${CORS_ORIGINS}
          - name: PPR_API_AUTH_API_URL
            value: ${AUTH_API_URL}
          - name: PPR_API_PAY_API_URL
            value: ${PAY_API_URL}
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                key: DSN
                name: sentry
          - name: SENTRY_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                key: ENVIRONMENT
                name: sentry
          - name: WEB_CONCURRENCY
            value: "4"
          envFrom:
            - prefix: PPR_API_DB_
              secretRef:
                name: ppr-database
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /operations/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${API_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /operations/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${API_NAME}
        from:
          kind: ImageStreamTag
          name: ${API_NAME}:${IMAGE_TAG}
          namespace: zwmtib-tools
      type: ImageChange
- apiVersion: v1
  kind: Secret
  metadata:
    name: ppr-database
  stringData:
    HOSTNAME: ${DB_HOSTNAME}
    HOSTNAME_PATRONI: ${DB_HOSTNAME_PATRONI}
    NAME: ${DB_NAME}
    PASSWORD: ${DB_PASSWORD}
    PORT: ${DB_PORT}
    USERNAME: ${DB_USERNAME}
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: sentry
  stringData:
    DSN: ${SENTRY_DSN}
    ENVIRONMENT: ${ENVIRONMENT}
  type: Opaque
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ppr
      environment: ${ENVIRONMENT}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${API_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ppr
      environment: ${ENVIRONMENT}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    host: ${ROUTE_URL}
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${API_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name of the API.
  displayName: API Name
  name: API_NAME
  required: true
  value: ppr-api
- description: The path to the SBC Auth API.
  displayName: Auth API URL
  name: AUTH_API_URL
  required: true
  value: https://auth-api-dev.pathfinder.gov.bc.ca/api/v1
- description: The origin urls for the web front ends that consume the API.
  displayName: Allowed origins for CORS
  name: CORS_ORIGINS
  required: true
  value: "http://localhost:8080 https://dev.bcregistry.ca https://ppr-dev.pathfinder.gov.bc.ca"
- description: Hostname of the EDB database server
  displayName: EDB Host
  name: DB_HOSTNAME
  required: true
  value: sbc-dev-service.hak2zo-dev.svc
- description: Hostname of the Patroni database server
  displayName: Patroni Host
  name: DB_HOSTNAME_PATRONI
  required: true
  value: patroni-master.zwmtib-dev.svc
- description: The name of both the Patroni and EDB database instances
  displayName: Database Name
  name: DB_NAME
  required: true
  value: ppr-dev
- description: The password for the database user
  displayName: Database Password
  name: DB_PASSWORD
  required: true
- description: The port of the EDB database server
  displayName: EDB Port
  name: DB_PORT
  required: true
  value: "5444"
- description: The username used to access the databases
  displayName: Database Username
  name: DB_USERNAME
  required: true
- description: The environment, such as "dev", "dev-pr13", "test", or "prod".
  displayName: Environment
  name: ENVIRONMENT
  required: true
  value: dev
- description: The image tag to deploy from.
  displayName: Image Tag
  name: IMAGE_TAG
  required: true
  value: dev
- description: The path to the Payment API.
  displayName: Payment API URL
  name: PAY_API_URL
  required: true
  value: https://pay-api-dev.pathfinder.gov.bc.ca/api/v1
- description: The URL to use for the route.
  displayName: Route URL
  name: ROUTE_URL
  required: true
  value: ppr-api-dev.pathfinder.gov.bc.ca
- description: A Sentry DSN as described in https://docs.sentry.io/error-reporting/quickstart/?platform=javascript#configure-the-sdk
  displayName: Sentry DSN
  name: SENTRY_DSN
  required: true
