apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ppr
      deploymentconfig: ${API_NAME}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      app: ppr
      deploymentconfig: ${API_NAME}
      environment: ${ENVIRONMENT}
      role: ${API_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ppr
          deploymentconfig: ${API_NAME}
          environment: ${ENVIRONMENT}
          role: ${API_NAME}
      spec:
        containers:
        - env:
          - name: PORT
            value: "8080"
          - name: WEB_CONCURRENCY
            value: "4"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ${API_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${API_NAME}
        from:
          kind: ImageStreamTag
          name: ${API_NAME}:${IMAGE_TAG}
          namespace: zwmtib-tools
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ppr
      environment: ${ENVIRONMENT}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${API_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ppr
      environment: ${ENVIRONMENT}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    host: ${ROUTE_URL}
    port:
      targetPort: 8080-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${API_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name of the API.
  displayName: API Name
  name: API_NAME
  required: true
  value: ppr-api
- description: The environment, such as "dev", "dev-pr13", "test", or "prod".
  displayName: Environment
  name: ENVIRONMENT
  required: true
  value: dev
- description: The image tag to build from.
  displayName: Image Tag
  name: IMAGE_TAG
  required: true
  value: dev
- description: The URL to use for the route.
  displayName: Route URL
  name: ROUTE_URL
  required: true
  value: ppr-api-dev.pathfinder.gov.bc.ca
