apiVersion: template.openshift.io/v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ppr
      build: ${API_NAME}
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: ${API_NAME}:latest
    source:
      contextDir: ppr-api
      dockerfile: |
        FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7-2019-10-15

        COPY ./src /app
        COPY ./requirements.txt /tmp
        RUN pip install -r /tmp/requirements.txt
      git:
        uri: https://github.com/bcgov/ppr
        # sample how to use a developer's fork
        # uri: https://github.com/somedeveloper/ppr
        # Defaults to shallow clone of master so no need to ref master. If you do set ref to master then clone is deep
        # Sample to show how to override to a branch
        # ref: branch
      type: Git
    strategy:
      dockerStrategy: {}
    successfulBuildsHistoryLimit: 5
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ppr
      role: ${API_NAME}
    name: ${API_NAME}
  spec:
    lookupPolicy:
      local: false
parameters:
- description: The name of the API
  displayName: API Name
  name: API_NAME
  required: true
  value: ppr-api
