openapi: 3.0.0
info:
  title: Personal Property Registry API
  version: '1.0'
  description: PPR API Specs
  contact:
    name: BC Registries
servers:
  - url: 'http://localhost:3100'
    description: Mock
  - url: 'https://ppr-api-dev.pathfinder.gov.bc.ca'
    description: Development
  - url: 'https://ppr-api-test.pathfinder.gov.bc.ca'
    description: Test
  - url: 'https://ppr-api.pathfinder.gov.bc.ca'
    description: Production
paths:
  /searches:
    get:
      summary: List previously submitted searches
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search'
              examples: {}
      operationId: get-searches
      parameters: []
      security:
        - JWT: []
    post:
      summary: 'Submit a new PPR search request '
      tags: []
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
              examples:
                Search Response:
                  value:
                    ref: /searches/95110d7f-91ce-47f2-a996-76e2dddc3cf7
                    type: SERIAL_NUMBER
                    criteria:
                      value: '1234'
                    results: /searches/95110d7f-91ce-47f2-a996-76e2dddc3cf7/results
                    searchDateTime: '2020-01-02T21:57:00Z'
                    payment:
                      id: 1234
                      status: CREATED
                      method: CC
            application/xml:
              schema:
                type: object
                properties: {}
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: post-search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/search'
            examples:
              Search by Serial Number:
                value:
                  type: SERIAL_NUMBER
                  criteria:
                    value: '1234'
              Search by Registration Number:
                value:
                  type: REGISTRATION_NUMBER
                  criteria:
                    value: 123456B
              Search by Debtor Name:
                value:
                  type: INDIVIDUAL_DEBTOR
                  criteria:
                    debtorName:
                      first: Homer
                      second: Jay
                      last: Simpson
      description: Initiates a new search transaction and will return a reference that can be used to review the results
      security:
        - JWT: []
  '/searches/{searchId}':
    get:
      summary: View the details for an individual search
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: get-search-for-id
      security:
        - JWT: []
    parameters:
      - schema:
          type: string
        name: searchId
        in: path
        required: true
  '/financing-statements/{financingStatementId}':
    parameters:
      - schema:
          type: string
        name: financingStatementId
        in: path
        required: true
        description: ''
    get:
      summary: View a financing statement
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financing-statement'
              examples: {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: get-financing-statement-for-id
      parameters:
        - schema:
            type: integer
          in: query
          name: version
          description: The version of the record to retrieve.  If not specified the most recent version will be retrieved.
      description: ''
      security:
        - JWT: []
  '/searches/{searchId}/results':
    parameters:
      - schema:
          type: string
        name: searchId
        in: path
        required: true
    get:
      summary: List results for a search
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search-result'
              examples:
                Example:
                  value:
                    - type: EXACT
                      financingStatement:
                        ref: /financing-statements/95110d7f-91ce-47f2-a996-76e2dddc3cf7?version=1
                        type: SECURITY_AGREEMENT
                        registeringParty:
                          name: Name of party
                          address: 123 Fake St
                          city: Victoria
                          province: BC
                          postalCode: A1A 1A1
                        securedParties:
                          - name: Name of party
                            address: 123 Fake St
                            city: Victoria
                            province: BC
                            postalCode: A1A 1A1
                        debtors:
                          - name: string
                        vehicleCollateral:
                          - type: MOTOR_VEHICLE
                            serial: WDBKK49F81F234840
                            year: 2001
                            model: Mercedes-Benz SLK-Class Kompressor
                        generalCollateral:
                          - description: Detailed description of general collateral
                        expiryDate: '2021-01-02'
                        baseRegistrationNumber: '1000123'
                        documentId: D0000123
                        registrationDateTime: '2020-01-02T21:08:32Z'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: get-search-matches
      description: Display the financing statements that were found with the search criteria
      security:
        - JWT: []
  /financing-statements:
    post:
      summary: Create a financing statement
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financing-statement'
              examples:
                New Financing Statement:
                  value:
                    type: SECURITY_AGREEMENT
                    registeringParty:
                      name:
                        first: Homer
                        last: Simpson
                        middle: Jay
                      address: 742 Evergreen Terrace
                      city: Springfield
                      province: BC
                      postalCode: A1A 1A1
                    securedParties:
                      - code: string
                        name: string
                        address: string
                        city: string
                        province: string
                        postalCode: string
                    debtors:
                      - name: string
                    vehicleCollateral:
                      - type: MOTOR_VEHICLE
                        serial: string
                        year: 1000
                        model: string
                        manufacturedHomeRegNumber: string
                    generalCollateral:
                      - description: string
                    expiryDate: '2020-02-21'
                    baseRegistrationNumber: string
                    documentId: string
                    registrationDateTime: '2020-02-21T18:38:20Z'
                    years: 1
        '422':
          description: Unprocessable Entity
      operationId: post-financing-statements
      description: Create a new financing statement record
      security:
        - JWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/financing-statement'
            examples:
              Register Financing Statement:
                value:
                  type: SECURITY_AGREEMENT
                  registeringParty:
                    name:
                      first: Homer
                      last: Simpson
                      middle: Jay
                    address: 742 Evergreen Terrace
                    city: Springfield
                    province: BC
                    postalCode: A1A 1A1
                  securedParties: []
                  debtors: []
                  vehicleCollateral: []
                  generalCollateral: []
                  years: 5
components:
  schemas:
    search:
      title: search
      type: object
      x-examples: {}
      description: ''
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - INDIVIDUAL_DEBTOR
            - BUSINESS_DEBTOR
            - MHR_NUMBER
            - REGISTRATION_NUMBER
            - SERIAL_NUMBER
            - AIRCRAFT_DOT
        criteria:
          type: object
          properties:
            value:
              type: string
            debtorName:
              type: object
              properties:
                first:
                  type: string
                second:
                  type: string
                last:
                  type: string
        results:
          type: string
          format: uri
          example: /searches/searchId/results
        searchDateTime:
          type: string
          format: date-time
        payment:
          $ref: '#/components/schemas/payment'
      required:
        - type
        - criteria
    financing-statement:
      title: financing-statement
      type: object
      description: ''
      x-examples: {}
      properties:
        type:
          type: string
          enum:
            - SECURITY_AGREEMENT
            - REPAIRERS_LIEN
        registeringParty:
          type: object
          properties:
            code:
              type: string
            name:
              $ref: '#/components/schemas/individual-name'
            address:
              type: string
            city:
              type: string
            province:
              type: string
            postalCode:
              type: string
        securedParties:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              name:
                type: string
              address:
                type: string
              city:
                type: string
              province:
                type: string
              postalCode:
                type: string
        debtors:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
        vehicleCollateral:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                  - MOTOR_VEHICLE
                  - BOAT
                  - MANUFACTURED_HOME
                  - OUTBOARD_MOTOR
                  - TRAILER
                  - AIRFRAME_REGISTERED_IN_CANADA
                  - AIRFRAME_NOT_REGISTERED_IN_CANADA
              serial:
                type: string
              year:
                type: integer
                minimum: 1000
                maximum: 9999
              model:
                type: string
              manufacturedHomeRegNumber:
                type: string
            required:
              - type
              - serial
              - model
        generalCollateral:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
            required:
              - description
        expiryDate:
          type: string
          format: date
        baseRegistrationNumber:
          type: string
        registrationDateTime:
          type: string
          format: date-time
        years:
          type: integer
          minimum: 1
          maximum: 25
          description: Length of the registration in years. Must be a value from 1 to 25.
      required:
        - type
        - securedParties
        - debtors
        - years
    search-result:
      type: object
      properties:
        type:
          type: string
          enum:
            - EXACT
            - SIMILAR
        financingStatement:
          $ref: '#/components/schemas/financing-statement'
    error:
      title: error
      type: object
      properties:
        code:
          type: string
          description: Identifier representing the type of error that occurred
        description:
          type: string
          description: Description of the error
      description: Contains details of an error that was encountered
    payment:
      title: payment
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
          enum:
            - CREATED
            - COMPLETED
            - TRANSACTION_FAILED
        method:
          type: string
          enum:
            - CC
    individual-name:
      title: individual-name
      type: object
      properties:
        first:
          type: string
        last:
          type: string
        middle:
          type: string
      required:
        - first
        - last
  securitySchemes:
    JWT:
      type: http
      scheme: Bearer
