openapi: 3.0.0
info:
  title: Personal Property Registry API
  version: '1.0'
  description: 'The Personal Property Register (PPR) is a centralized register where legal claims to personal property can be registered, and consumers can check if there is any debt or obligation attached to goods they may wish to buy. The PPR API provides a real-time, secure, direct link between business systems and the PPR. Most PPR transactions, including searches, registrations, renewals, amendments and discharges, directly from your own software, instead of using the PPR website.'
  contact:
    name: BC Registries
servers:
  - url: 'http://localhost:3100'
    description: Mock
  - url: 'https://ppr-api-dev.pathfinder.gov.bc.ca'
    description: Development
  - url: 'https://ppr-api-test.pathfinder.gov.bc.ca'
    description: Test
  - url: 'https://ppr-api.pathfinder.gov.bc.ca'
    description: Production
paths:
  /searches:
    get:
      summary: List previously submitted searches
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search'
              examples: {}
      operationId: get-searches
      parameters:
        - schema:
            type: string
          in: header
          name: Account-Id
          description: The account that the user is operating on behalf of
          required: true
      security:
        - JWT: []
      description: The system will list previously submitted searches
    post:
      summary: 'Submit a new PPR search request '
      tags:
        - Search
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
              examples:
                Search Response:
                  value:
                    ref: /searches/95110d7f-91ce-47f2-a996-76e2dddc3cf7
                    type: SERIAL_NUMBER
                    criteria:
                      value: '1234'
                    results: /searches/95110d7f-91ce-47f2-a996-76e2dddc3cf7/results
                    searchDateTime: '2020-01-02T21:57:00Z'
                    payment:
                      id: 1234
                      status: CREATED
                      method: CC
            application/xml:
              schema:
                type: object
                properties: {}
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: post-search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/search'
            examples:
              Search by Serial Number:
                value:
                  type: SERIAL_NUMBER
                  criteria:
                    value: '1234'
              Search by Registration Number:
                value:
                  type: REGISTRATION_NUMBER
                  criteria:
                    value: 123456B
              Search by Debtor Name:
                value:
                  type: INDIVIDUAL_DEBTOR
                  criteria:
                    debtorName:
                      first: Homer
                      second: Jay
                      last: Simpson
      description: 'Submit a new search transaction and will return a {searchId} that can be used to review the results'
      security:
        - JWT: []
      parameters:
        - schema:
            type: string
          in: header
          name: Account-Id
          description: The account that the user is operating on behalf of
          required: true
  '/searches/{searchId}':
    get:
      summary: View the details for an individual search
      tags:
        - Search
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: get-search-for-id
      security:
        - JWT: []
      parameters:
        - schema:
            type: string
          in: header
          name: Account-Id
          description: The account that the user is operating on behalf of
          required: true
      description: 'To get the meta-data around your search, supply the search id you received after submitting your search criteria using POST.'
    parameters:
      - schema:
          type: string
        name: searchId
        in: path
        required: true
        description: 'The value of the search response id value.  If an invalid searchId is submitted then [404].'
  '/financing-statements/{financingStatementId}':
    parameters:
      - schema:
          type: string
        name: financingStatementId
        in: path
        required: true
        description: 'A base registration number that is valid and not expired.  If {financingStatementId} is not found, then [404]'
    get:
      summary: View a financing statement
      tags:
        - Financing Statement
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financing-statement'
              examples: {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: get-financing-statement-for-id
      parameters:
        - schema:
            type: string
          in: header
          name: Account-Id
          description: The account that the user is operating on behalf of
          required: true
      description: View a financing statement
      security:
        - JWT: []
  '/searches/{searchId}/results':
    parameters:
      - schema:
          type: string
        name: searchId
        in: path
        required: true
        description: 'The value of the search response id value.  If an invalid searchId is submitted then [404].'
    get:
      summary: List results for a search
      tags:
        - Search
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search-result'
              examples:
                Example:
                  value:
                    - type: EXACT
                      financingStatement:
                        ref: /financing-statements/95110d7f-91ce-47f2-a996-76e2dddc3cf7?version=1
                        type: SECURITY_AGREEMENT
                        registeringParty:
                          businessName: Name of party
                          address:
                            street: 123 Fake St
                            city: Victoria
                            region: BC
                            country: CA
                            postalCode: A1A 1A1
                        securedParties:
                          - businessName: Name of party
                            address:
                              street: 123 Fake St
                              city: Victoria
                              region: BC
                              country: CA
                              postalCode: A1A 1A1
                        debtors:
                          - businessName: Debtor Name
                        vehicleCollateral:
                          - type: MOTOR_VEHICLE
                            serial: WDBKK49F81F234840
                            year: 2001
                            make: Mercedes-Benz
                            model: SLK-Class Kompressor
                        generalCollateral:
                          - description: Detailed description of general collateral
                        expiryDate: '2021-01-02'
                        baseRegistrationNumber: '1000123'
                        documentId: D0000123
                        registrationDateTime: '2020-01-02T21:08:32Z'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      operationId: get-search-matches
      description: Displays the Financing Statement records found with the search criteria referenced by searchId.
      security:
        - JWT: []
      parameters:
        - schema:
            type: string
          in: header
          name: Account-Id
          description: The account that the user is operating on behalf of
          required: true
  /financing-statements:
    post:
      summary: Create a financing statement
      tags:
        - Financing Statement
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financing-statement'
              examples:
                New Financing Statement:
                  value:
                    type: SECURITY_AGREEMENT
                    registeringParty:
                      personName:
                        first: Homer
                        last: Simpson
                        middle: Jay
                      address:
                        street: 742 Evergreen Terrace
                        city: Springfield
                        region: BC
                        country: CA
                        postalCode: A1A 1A1
                    securedParties:
                      - businessName: Spacely Sprockets
                        address:
                          street: 123 Fake St
                          streetAdditional: Suite 501
                          city: Jupiter
                          region: BC
                          country: CA
                          postalCode: A1A 1A1
                    debtors:
                      - businessName: My Company Inc
                        address:
                          street: 721 Debtor Ave
                          city: Victoria
                          region: BC
                          country: CA
                          postalCode: A1A 1A1
                        birthdate: '1990-06-15'
                    vehicleCollateral:
                      - type: MOTOR_VEHICLE
                        serial: WDBKK49F81F234840
                        year: 2001
                        make: Mercedes-Benz
                        model: SLK-Class Kompressor
                    generalCollateral:
                      - description: A ride on lawn mower that has a great deal of personal value
                    expiryDate: '2020-02-21'
                    baseRegistrationNumber: 791167G
                    documentId: B5645289
                    registrationDateTime: '2020-02-21T18:38:20Z'
                    years: 5
        '422':
          description: Unprocessable Entity
      operationId: post-financing-statements
      description: Create (register) a new financing statement
      security:
        - JWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/financing-statement'
            examples:
              Register Financing Statement:
                value:
                  type: SECURITY_AGREEMENT
                  registeringParty:
                    personName:
                      first: Homer
                      last: Simpson
                      middle: Jay
                    address:
                      street: 742 Evergreen Terrace
                      city: Springfield
                      region: BC
                      country: CA
                      postalCode: A1A 1A1
                  securedParties:
                    - businessName: Spacely Sprockets
                      address:
                        street: 123 Fake St
                        streetAdditional: Suite 501
                        city: Jupiter
                        region: BC
                        country: CA
                        postalCode: A1A 1A1
                  debtors:
                    - businessName: My Company Inc
                      address:
                        street: 721 Debtor Ave
                        city: Victoria
                        region: BC
                        country: CA
                        postalCode: A1A 1A1
                      birthdate: '1990-06-15'
                  vehicleCollateral:
                    - type: MOTOR_VEHICLE
                      serial: WDBKK49F81F234840
                      year: 2001
                      make: Mercedes-Benz
                      model: SLK-Class Kompressor
                  generalCollateral:
                    - description: A ride on lawn mower that has a great deal of personal value
                  years: 5
      parameters:
        - schema:
            type: string
          in: header
          name: Account-Id
          description: The account that the user is operating on behalf of
          required: true
components:
  schemas:
    search:
      title: search
      type: object
      x-examples: {}
      description: ''
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - INDIVIDUAL_DEBTOR
            - BUSINESS_DEBTOR
            - MHR_NUMBER
            - REGISTRATION_NUMBER
            - SERIAL_NUMBER
            - AIRCRAFT_DOT
        criteria:
          type: object
          properties:
            value:
              type: string
            debtorName:
              type: object
              properties:
                first:
                  type: string
                second:
                  type: string
                last:
                  type: string
        searchDateTime:
          type: string
          format: date-time
        payment:
          $ref: '#/components/schemas/payment'
      required:
        - type
        - criteria
    financing-statement:
      title: financing-statement
      type: object
      description: ''
      x-examples: {}
      properties:
        type:
          type: string
          enum:
            - SECURITY_AGREEMENT
            - REPAIRERS_LIEN
            - MFD_HOME_SEPARATION_AGREEMENT
            - MFD_HOME_LAND_TAX_DEFERMENT
            - MFD_HOME_TAX_LIEN
            - SALE_OF_GOODS_ACT_POSSESSION
            - FORESTRY_CONTRACTOR_LIEN
            - FORESTRY_CONTRACTOR_CHARGE
            - FORESTRY_SUBCONTRACTOR_CHARGE
            - MISCELLANEOUS_REGISTRATION
        registeringParty:
          type: object
          properties:
            code:
              type: string
            personName:
              $ref: '#/components/schemas/individual-name'
            businessName:
              type: string
            address:
              $ref: '#/components/schemas/address'
          required:
            - address
        securedParties:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              personName:
                $ref: '#/components/schemas/individual-name'
              businessName:
                type: string
              address:
                $ref: '#/components/schemas/address'
            required:
              - address
        debtors:
          type: array
          items:
            type: object
            properties:
              personName:
                $ref: '#/components/schemas/individual-name'
              businessName:
                type: string
              address:
                $ref: '#/components/schemas/address'
              birthdate:
                type: string
                description: Date of birth in ISO 8601 format
                format: date
            required:
              - address
        vehicleCollateral:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                  - MOTOR_VEHICLE
                  - BOAT
                  - MANUFACTURED_HOME
                  - OUTBOARD_MOTOR
                  - TRAILER
                  - AIRCRAFT
                  - AIRCRAFT_FRAME
                  - ELECTRIC_VEHICLE
              serial:
                type: string
              year:
                type: integer
                minimum: 1000
                maximum: 9999
              make:
                type: string
              model:
                type: string
              manufacturedHomeRegNumber:
                type: string
            required:
              - type
              - serial
        generalCollateral:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
            required:
              - description
        expiryDate:
          type: string
          format: date
        baseRegistrationNumber:
          type: string
        registrationDateTime:
          type: string
          format: date-time
        years:
          type: integer
          minimum: 1
          maximum: 25
          description: Length of the registration in years. Must be a value from 1 to 25.
      required:
        - type
        - securedParties
        - debtors
        - years
    search-result:
      type: object
      properties:
        type:
          type: string
          enum:
            - EXACT
            - SIMILAR
        financingStatement:
          $ref: '#/components/schemas/financing-statement'
    error:
      title: error
      type: object
      properties:
        code:
          type: string
          description: Identifier representing the type of error that occurred
        description:
          type: string
          description: Description of the error
      description: Contains details of an error that was encountered
    individual-name:
      title: individual-name
      type: object
      properties:
        first:
          type: string
        last:
          type: string
        middle:
          type: string
      required:
        - first
        - last
    payment:
      title: payment
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
          enum:
            - CREATED
            - COMPLETED
            - TRANSACTION_FAILED
        method:
          type: string
          enum:
            - CC
    address:
      title: address
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        region:
          type: string
          description: 'For Canada or USA, 2 character region code'
          minLength: 2
          maxLength: 2
        country:
          type: string
          minLength: 2
          maxLength: 2
          description: 2 Character ISO 3166-1 Alpha-2 Country Code
        postalCode:
          type: string
        streetAdditional:
          type: string
      required:
        - street
        - city
        - country
        - postalCode
  securitySchemes:
    JWT:
      type: http
      scheme: Bearer
tags:
  - name: Financing Statement
  - name: Search
