openapi: 3.0.0
info:
  title: Personal Property Registry API
  version: '1.0'
  description: PPR API Specs
  contact:
    name: BC Registries
servers:
  - url: 'http://localhost:3100'
    description: Mock
  - url: 'https://ppr-api-dev.pathfinder.gov.bc.ca'
    description: Development
  - url: 'https://ppr-api-test.pathfinder.gov.bc.ca'
    description: Test
  - url: 'https://ppr-api.pathfinder.gov.bc.ca'
    description: Production
paths:
  /searches:
    get:
      summary: List previously submitted searches
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search'
              examples: {}
      operationId: get-searches
      parameters: []
    post:
      summary: 'Submit a new PPR search request '
      tags: []
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
              examples:
                Search Response:
                  value:
                    ref: /searches/95110d7f-91ce-47f2-a996-76e2dddc3cf7
                    type: SERIAL
                    criteria:
                      value: '1234'
                    results: /searches/95110d7f-91ce-47f2-a996-76e2dddc3cf7/results
                    searchDateTime: '2020-01-02T21:57:00Z'
            application/xml:
              schema:
                type: object
                properties: {}
      operationId: post-search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/search'
            examples:
              Search by Serial:
                value:
                  type: SERIAL
                  criteria:
                    value: '1234'
              Search by Base Registration Number:
                value:
                  type: REGISTRATION_NUMBER
                  criteria:
                    value: 123456B
              Search by Debtor Name:
                value:
                  type: INDIVIDUAL_DEBTOR
                  criteria:
                    debtorName:
                      first: Homer
                      second: J
                      last: Simpson
      description: Initiates a new search transaction and will return a reference that can be used to review the results
  '/searches/{searchId}':
    get:
      summary: View the details for an individual search
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
      operationId: get-search-for-id
    parameters:
      - schema:
          type: string
        name: searchId
        in: path
        required: true
  '/financing-statements/{financingStatementId}':
    parameters:
      - schema:
          type: string
        name: financingStatementId
        in: path
        required: true
        description: ''
    get:
      summary: View a financing statement
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/financing-statement'
              examples: {}
      operationId: get-financing-statement-for-id
      parameters:
        - schema:
            type: integer
          in: query
          name: version
          description: The version of the record to retrieve.  If not specified the most recent version will be retrieved.
      description: ''
  '/searches/{searchId}/results':
    parameters:
      - schema:
          type: string
        name: searchId
        in: path
        required: true
    get:
      summary: List results for a search
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/search-result'
              examples:
                Example:
                  value:
                    - type: EXACT
                      financingStatement:
                        ref: /financing-statements/95110d7f-91ce-47f2-a996-76e2dddc3cf7?version=1
                        type: SECURITY_AGREEMENT
                        registeringParty:
                          name: Name of party
                          address: 123 Fake St
                          city: Victoria
                          province: BC
                          postalCode: A1A 1A1
                        securedParties:
                          - name: Name of party
                            address: 123 Fake St
                            city: Victoria
                            province: BC
                            postalCode: A1A 1A1
                        debtors:
                          - name: string
                        vehicleCollateral:
                          - type: MOTOR_VEHICLE
                            serial: WDBKK49F81F234840
                            year: 2001
                            model: Mercedes-Benz SLK-Class Kompressor
                        generalCollateral:
                          - description: Detailed description of general collateral
                        expiryDate: '2021-01-02'
                        baseRegistrationNumber: '1000123'
                        documentId: D0000123
                        registrationDateTime: '2020-01-02T21:08:32Z'
      operationId: get-search-matches
      description: Display the financing statements that were found with the search criteria
components:
  schemas:
    search:
      title: search
      type: object
      x-examples: {}
      description: ''
      properties:
        ref:
          type: string
          format: uri
        type:
          type: string
          enum:
            - SERIAL
            - INDIVIDUAL_DEBTOR
            - BUSINESS_DEBTOR
            - MHR_NUMBER
            - REGISTRATION_NUMBER
            - AIRCRAFT_DOT
        criteria:
          type: object
          properties:
            value:
              type: string
            debtorName:
              type: object
              properties:
                first:
                  type: string
                second:
                  type: string
                last:
                  type: string
        results:
          type: string
          format: uri
          example: /searches/searchId/results
        searchDateTime:
          type: string
          format: date-time
      required:
        - criteria
        - type
    financing-statement:
      title: financing-statement
      type: object
      description: ''
      x-examples: {}
      properties:
        ref:
          type: string
          format: uri
        type:
          type: string
          enum:
            - SECURITY_AGREEMENT
            - REPAIRERS_LIEN
        registeringParty:
          type: object
          properties:
            code:
              type: string
            name:
              type: string
            address:
              type: string
            city:
              type: string
            province:
              type: string
            postalCode:
              type: string
        securedParties:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              name:
                type: string
              address:
                type: string
              city:
                type: string
              province:
                type: string
              postalCode:
                type: string
        debtors:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
        vehicleCollateral:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                  - MOTOR_VEHICLE
                  - BOAT
                  - MANUFACTURED_HOME
                  - OUTBOARD_MOTOR
                  - TRAILER
                  - AIRFRAME_REGISTERED_IN_CANADA
                  - AIRFRAME_NOT_REGISTERED_IN_CANADA
              serial:
                type: string
              year:
                type: integer
                minimum: 1000
                maximum: 9999
              model:
                type: string
              manufacturedHomeRegNumber:
                type: string
            required:
              - type
              - serial
              - model
        generalCollateral:
          type: array
          items:
            type: object
            properties:
              description:
                type: string
            required:
              - description
        expiryDate:
          type: string
          format: date
        baseRegistrationNumber:
          type: string
        documentId:
          type: string
        registrationDateTime:
          type: string
          format: date-time
      required:
        - type
        - securedParties
        - debtors
    search-result:
      type: object
      properties:
        type:
          type: string
          enum:
            - EXACT
            - SIMILAR
        financingStatement:
          $ref: '#/components/schemas/financing-statement'
  securitySchemes: {}
