/**
 * Enumerates the types of collateral that are identified by serial numbers.
 */
export enum SerialCollateralType {
  AIRCRAFT = 'AIRCRAFT',
  AIRCRAFT_FRAME = 'AIRCRAFT_FRAME',
  BOAT = 'BOAT',
  ELECTRIC_VEHICLE = 'ELECTRIC_VEHICLE',
  MANUFACTURED_HOME_NOT_REGISTERED = 'MANUFACTURED_HOME_NOT_REGISTERED',
  MANUFACTURED_HOME_REGISTERED = 'MANUFACTURED_HOME_REGISTERED',
  MOTOR_VEHICLE = 'MOTOR_VEHICLE',
  OUTBOARD_MOTOR = 'OUTBOARD_MOTOR',
  TRAILER = 'TRAILER'
}

export const serialCollateralTypeCodeList: string[] = [
  'MOTOR_VEHICLE',
  'ELECTRIC_VEHICLE',
  'TRAILER',
  'AIRCRAFT',
  'AIRCRAFT_FRAME',
  'BOAT',
  'OUTBOARD_MOTOR',
  'MANUFACTURED_HOME_NOT_REGISTERED',
  'MANUFACTURED_HOME_REGISTERED'
]
