export enum FinancingStatementType {
  SECURITY_AGREEMENT = 'SECURITY_AGREEMENT',
  REPAIRERS_LIEN = 'REPAIRERS_LIEN',
  MFD_HOME_SEPARATION_AGREEMENT = 'MFD_HOME_SEPARATION_AGREEMENT',
  MFD_HOME_LAND_TAX_DEFERMENT = 'MFD_HOME_LAND_TAX_DEFERMENT',
  MFD_HOME_TAX_LIEN = 'MFD_HOME_TAX_LIEN',
  SALE_OF_GOODS_ACT_POSSESSION = 'SALE_OF_GOODS_ACT_POSSESSION',
  FORESTRY_CONTRACTOR_LIEN = 'FORESTRY_CONTRACTOR_LIEN',
  FORESTRY_CONTRACTOR_CHARGE = 'FORESTRY_CONTRACTOR_CHARGE',
  FORESTRY_SUBCONTRACTOR_CHARGE = 'ORESTRY_SUBCONTRACTOR_CHARGE',
  MISCELLANEOUS_REGISTRATION = 'MISCELLANEOUS_REGISTRATION',
}

// TODO: provide a mapping function from the enum to a human readable string, such as "PPSA Security Agreement"
