export enum FinancingStatementType {
  SECURITY_AGREEMENT = 'SECURITY_AGREEMENT',
  REPAIRERS_LIEN = 'REPAIRERS_LIEN'
  /*
  SALE_OF_GOODS
  FORESTRY CONTRACTOR LIEN
  FORESTRY CONTRACTOR CHARGE
  FORESTRY SUBCONTRACTOR CHARGE
  TAX LIEN
  LAND TAX
  NOTICE OF MARRIAGE ...
  */
}

export const FinancingStatementTypeCodeList = ['SECURITY_AGREEMENT', 'REPAIRERS_LIEN']
