name: Build Continuous Integration Artifacts

on:
  push:
    branches: [master]

jobs:
  ims-api-image-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build the Spring Boot distribution
        working-directory: ims-api
        run: ./gradlew bootDistTar
      - name: Build the Docker image
        run: docker image build ims-api --tag ims-api:$GITHUB_SHA
# TODO Once we have full access to Artifactory, push the image to the repository
#      - name: Build the Docker image
#        run: docker image push ims-api:$GITHUB_SHA

# TODO: Once other jobs are complete, we may bring up some services and run a small suite of integration tests, if we wish
#  e2e-test:
#    needs: ims-api-image-build
#    runs-on: ubuntu-latest
#    # services: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idservices
#    # steps: TODO run the suite of tests
# TODO Upon successful completion of all tests, re-tag the image as "dev" and push again
#      - name: Tag the new image as Dev
#        run: |
#          docker image tag ims-api:$GITHUB_SHA ims-api:dev
#          docker image push ims-api:dev
