name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ppr-api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
    - name: Lint with PyLint
      working-directory: ppr-api
      run: |
        pylint -E app
#     - name: Test with pytest
#       working-directory: ppr-api
#       run: |
#         pip install pytest
#         pytest
